# Generated by Django 4.2.6 on 2023-10-23 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_ceo', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('inception_Date', models.DateField()),
            ],
        ),
    ]
